### ISSUE TITLE
Documentation Build Failing on GitHub Actions

### ISSUE THREAD

**Issue by shubham-0819** [code4kill/askpdf#2]
**Description**: The GitHub Actions workflow for building and deploying the Jekyll site to GitHub Pages is failing. As a collaborator, I suspect the issue might be related to permissions or a misconfiguration in the build setup.
**Steps to Reproduce**:

1. Push changes to the `main` branch.
2. Observe the GitHub Actions workflow execution.

**Expected Behavior**: The workflow should successfully build the Jekyll site and deploy it to GitHub Pages.
**Actual Behavior**: The workflow fails during the build or deploy step.

**Workflow Configuration**: Here is the relevant section of the workflow configuration from `.github/workflows/jekyll-docker.yml`
```yaml
name: Jekyll Build and Deploy

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different
  pull_request:
    branches:
      - main  # Optionally run on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Specify the Ruby version needed for Jekyll

      - name: Install Jekyll and Bundler
        run: gem install jekyll bundler

      - name: Install dependencies
        run: bundle install

      - name: Build the site with Jekyll
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # The folder where Jekyll outputs the static files

```
